# Generated by Django 6.0.4 on 2026-04-27 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Dueño', 'Dueño'), ('Colaborador', 'Colaborador'), ('Veterinario', 'Veterinario'), ('Refugio', 'Refugio'), ('Municipalidad', 'Municipalidad'), ('Admin', 'Admin')], max_length=20)),
                ('aprobacion_org', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_push', models.BooleanField(default=True)),
                ('georeporte', models.BooleanField(default=True)),
                ('noti_email', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='usuarios_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='perfil_entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=100)),
                ('telefono_entidad', models.CharField(blank=True, max_length=20, null=True)),
                ('email_entidad', models.EmailField(blank=True, max_length=254, null=True)),
                ('ubicacion_entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_entidad', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_entidad', to='usuarios_app.usuario')),
            ],
        ),
    ]
