# Generated by Django 6.0.4 on 2026-05-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_entidad',
            old_name='usuario',
            new_name='usuario_perfil',
        ),
        migrations.RenameField(
            model_name='preferencia',
            old_name='usuario',
            new_name='usuario_preferencia',
        ),
    ]
