# Generated by Django 6.0.4 on 2026-05-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0003_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Dueno', 'Dueno'), ('Colaborador', 'Colaborador'), ('Veterinario', 'Veterinario'), ('Refugio', 'Refugio'), ('Municipalidad', 'Municipalidad'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
