# Generated by Django 6.0.4 on 2026-06-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=100)),
                ('tipo_entidad', models.CharField(choices=[('Refugio', 'Refugio'), ('Municipalidad', 'Municipalidad'), ('Veterinaria', 'Clínica Veterinaria')], max_length=20)),
                ('rut_entidad', models.CharField(max_length=12, unique=True)),
                ('telefono_entidad', models.CharField(blank=True, max_length=20, null=True)),
                ('email_entidad', models.EmailField(max_length=254)),
                ('ubicacion_entidad', models.CharField(max_length=255)),
                ('comuna_entidad', models.CharField(max_length=100)),
                ('descripcion_entidad', models.TextField(blank=True, null=True)),
                ('aprobacion_entidad', models.BooleanField(default=False)),
                ('fecha_creacion_entidad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil_entidad',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil_entidad',
            name='fecha_ingreso_perfil',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_entidad',
            name='rol_entidad',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador de entidad'), ('Trabajador', 'Trabajador/Empleado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Dueno', 'Dueño'), ('Colaborador', 'Colaborador'), ('Admin', 'Admin')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfil_entidad',
            name='entidad_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_entidad', to='usuarios_app.entidad'),
        ),
        migrations.AlterUniqueTogether(
            name='perfil_entidad',
            unique_together={('usuario_perfil', 'entidad_perfil')},
        ),
        migrations.RemoveField(
            model_name='perfil_entidad',
            name='descripcion_entidad',
        ),
        migrations.RemoveField(
            model_name='perfil_entidad',
            name='email_entidad',
        ),
        migrations.RemoveField(
            model_name='perfil_entidad',
            name='nombre_entidad',
        ),
        migrations.RemoveField(
            model_name='perfil_entidad',
            name='telefono_entidad',
        ),
        migrations.RemoveField(
            model_name='perfil_entidad',
            name='ubicacion_entidad',
        ),
    ]
